[platformio]
default_envs = cardputer_adv_recorder

[env:cardputer_adv_recorder]
platform = espressif32@6.7.0
board = esp32-s3-devkitc-1
framework = arduino
build_type = release
monitor_speed = 115200
upload_speed = 1500000
build_flags =
    -DESP32S3
    -DCORE_DEBUG_LEVEL=3
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DFIRMWARE_VERSION=\"recorder-0.3.0\"
lib_deps =
    https://github.com/m5stack/M5Cardputer.git#f1392858b9994c3547120e602a57d3553d16ab01
    https://github.com/m5stack/M5Unified.git#e79eb6e3137a41e50b0ec23c8c38738bdb3a11e2
    bblanchon/ArduinoJson@7.4.2
